version: "3"

services:
    reverse-proxy:
        image: "jwilder/nginx-proxy:1.0"
        container_name: "reverse-proxy"
        volumes:
            - "html:/usr/share/nginx/html"
            - "/var/lib/docker/nginx-volumes/dhparam:/etc/nginx/dhparam"
            - "/var/lib/docker/nginx-volumes/vhost.d:/etc/nginx/vhost.d"
            - "/var/lib/docker/nginx-volumes/certs:/etc/nginx/certs"
            - "/run/docker.sock:/tmp/docker.sock:ro"
        restart: "always"
        networks: 
            - "nginx"
        ports:
            - "80:80"
            - "443:443"
    letsencrypt:
        image: "nginxproxy/acme-companion:2.2"
        container_name: "letsencrypt-helper"
        volumes:
            - "html:/usr/share/nginx/html"
            - "/var/lib/docker/nginx-volumes/dhparam:/etc/nginx/dhparam"
            - "/var/lib/docker/nginx-volumes/vhost.d:/etc/nginx/vhost.d"
            - "/var/lib/docker/nginx-volumes/certs:/etc/nginx/certs"
            - "/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            NGINX_PROXY_CONTAINER: "reverse-proxy"
            DEFAULT_EMAIL: "user@oxiliatest.ydns.eu"
        restart: "always"
        depends_on:
            - "reverse-proxy"
        networks: 
            - "nginx"
volumes:
  html:

networks:
  nginx:
    external: true